### ISSUE TITLE
got multiple values for keyword argument 'lines'

### ISSUE THREAD

**Issue by xipurewhite** [hako-mikan/sd-webui-supermerger#18]
Error executing callback ui_tabs_callback for E:\AIDraw\stable-diffusion-webui_23-01-20\extensions\sd-webui-supermerger\scripts\supermerger.py
Traceback (most recent call last):
  File "E:\AIDraw\stable-diffusion-webui_23-01-20\modules\script_callbacks.py", line 106, in ui_tabs_callback
    res += c.callback() or []
  File "E:\AIDraw\stable-diffusion-webui_23-01-20\extensions\sd-webui-supermerger\scripts\supermerger.py", line 152, in on_ui_tabs
    weightstags= gr.TextArea(label="available",lines=2,value=tagdicter(weights_presets),visible =True,interactive =True)
  File "E:\AIDraw\stable-diffusion-webui_23-01-20\python\lib\site-packages\gradio\templates.py", line 23, in __init__
    super().__init__(lines=7, **kwargs)
TypeError: gradio.components.Textbox.__init__() got multiple values for keyword argument 'lines'

**Comment by hako-mikan** [comment]
Thanks reporting.
I have fixed the suspicious part. The problem was not reproduced in my environment, so please give it a try.

**Comment by yamisang0819** [comment]
I also met this problem. Have you solved it

**Comment by hako-mikan** [comment]
I fixed it yesterday. Does your problem still occur with the latest version?

**Comment by yamisang0819** [comment]
I have updated to the latest version, but the above problem still appears.

**Comment by hako-mikan** [comment]
Can you tell me what the error is?

**Comment by yamisang0819** [comment]
Error executing callback ui_tabs_callback for E:\stable-diffusion-webui_\extensions\sd-webui-supermerger\scripts\supermerger.py
Traceback (most recent call last):
  File "E:\stable-diffusion-webui_\modules\script_callbacks.py", line 119, in ui_tabs_callback
    res += c.callback() or []
  File "E:\stable-diffusion-webui_\extensions\sd-webui-supermerger\scripts\supermerger.py", line 182, in on_ui_tabs
    pluslora.on_ui_tabs()
  File "E:\stable-diffusion-webui_\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 78, in on_ui_tabs
    sml_loraratios = gr.TextArea(label="",lines=10,value=sml_lbwpresets,visible =True,interactive  = True)
  File "E:\stable-diffusion-webui_\python\lib\site-packages\gradio\templates.py", line 23, in __init__
    super().__init__(lines=7, **kwargs)
TypeError: gradio.components.Textbox.__init__() got multiple values for keyword argument 'lines'

This is my error message

**Comment by hako-mikan** [comment]
Thanks reporting!

It seems that there were two point that needed to be fixed. I have fixed them and you can try again. You need to restart web-ui for the effect to take effect.

**Comment by yamisang0819** [comment]
Thank you. The problem has been solved after the update.
